config/routes.rb
Rails.application.routes.draw do

  resources :shopping_details
  delete 'shopping_infos/delete_shopping_info'

  post 'shopping_infos/upload_shopping_info'

  get 'budgets/show_budget'

  resources :products

  resources :sales

  resources :favourite_stores

=begin
  resource :user do
    resource :users
  end
=end

  # noinspection RubyResolve
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks'}

  root 'smartlist_app#dashboard_user'

  get 'dashboard_admin' => 'smartlist_app#dashboard_admin', as: :dashboard_admin

  get 'dashboard_store' => 'smartlist_app#dashboard_store', as: :dashboard_store

  post 'contact_us' => 'smartlist_app#contact_us', as: :contact_us

  get '/show_all_sales', to: 'smartlist_app#show_all_sales'

  # Recipe routes
  get 'recipes/show_recipes'

  get 'recipes/set_recipe_as_active_list'

  get 'recipes/add_recipe_to_active_list'

  delete 'recipes/delete_recipe'

  get 'recipes/delete_product_from_recipe'

  get 'recipes/add_product_to_recipe'

  get 'recipes/edit_recipe'

  get 'recipes/create_recipe'

  get '/show_recipe_constructor', to: 'recipes#show_recipe_constructor'

  post '/register_new_recipe', to: 'recipes#register_new_recipe'

  # FavouriteList routes
  get 'favourite_lists/show_favourite_lists'

  get 'favourite_lists/make_favourite_list_active'

  delete 'favourite_lists/delete_favourite_list'

  get 'favourite_lists/edit_favourite_list'

  post 'favourite_lists/create_favourite_list'

  get '/delete_from_favourite_list', to: 'favourite_lists#delete_from_favourite_list'

  get '/add_to_favourite_list', to: 'favourite_lists#add_to_favourite_list'

  post '/send_list_by_mail', to: 'favourite_lists#send_list_by_mail'

  # Admin routes
  get 'admin/show_users'

  get 'admin/show_stores'

  get 'admin/show_user'

  get 'admin/new_user'

  get 'admin/new_store'

  get 'admin/edit_user'

  post 'admin/create_user'

  post 'admin/update_user'

  delete 'admin/destroy_user'


  # Product routes
  get 'shopping_list' => '/show_all_active_products', to: 'products#show_all_active_products'

  get '/set_as_active', to: 'products#set_as_active'

  get '/set_as_inactive', to: 'products#set_as_inactive'

end

app/models/shopping_detail.rb
class ShoppingDetail < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/shopping_details_controller.rb
class ShoppingDetailsController < ApplicationController
  before_action :set_shopping_detail, only: [:show, :edit, :update, :destroy]

  # GET /shopping_details
  # GET /shopping_details.json
  def index
    @shopping_details = ShoppingDetail.where(user_id: current_user.id)
  end

  # GET /shopping_details/1
  # GET /shopping_details/1.json
  def show
  end

  # GET /shopping_details/new
  def new
    @shopping_detail = ShoppingDetail.new
  end

  # GET /shopping_details/1/edit
  def edit
  end

  # POST /shopping_details
  # POST /shopping_details.json
  def create
    @shopping_detail = ShoppingDetail.new(shopping_detail_params)

    respond_to do |format|
      if @shopping_detail.save
        format.html { redirect_to @shopping_detail, notice: 'Shopping detail was successfully created.' }
        format.json { render :show, status: :created, location: @shopping_detail }
      else
        format.html { render :new }
        format.json { render json: @shopping_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopping_details/1
  # PATCH/PUT /shopping_details/1.json
  def update
    respond_to do |format|
      if @shopping_detail.update(shopping_detail_params)
        format.html { redirect_to @shopping_detail, notice: 'Shopping detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @shopping_detail }
      else
        format.html { render :edit }
        format.json { render json: @shopping_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_details/1
  # DELETE /shopping_details/1.json
  def destroy
    @shopping_detail.destroy
    respond_to do |format|
      format.html { redirect_to shopping_details_url, notice: 'Shopping detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_detail
      @shopping_detail = ShoppingDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopping_detail_params
      params.require(:shopping_detail).permit(:image, :description, :user_id)
    end
end

app/helpers/shopping_details_helper.rb
module ShoppingDetailsHelper
end

app/views/shopping_details/_form.html.erb
<%= form_for @shopping_detail, url: shopping_details_path, html: {multipart: true} do |f| %>
    <% if @shopping_detail.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@shopping_detail.errors.count, "error") %> prohibited this shopping_detail from being
            saved:</h2>

          <ul>
            <% @shopping_detail.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>
    
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/shopping_details/edit.html.erb
<h1>Editing Shopping Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @shopping_detail %> |
<%= link_to 'Back', shopping_details_path %>

app/views/shopping_details/index.html.erb
<h1>Shopping Details</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shopping_details.each do |shopping_detail| %>
      <tr>
        <td><%= image_tag shopping_detail.image.url(:medium) %></td>
        <td class="col-xs-6 left-al-cell"><%= shopping_detail.description %></td>
        <td><%= link_to 'Show', shopping_detail %></td>
        <td><%= link_to 'Edit', edit_shopping_detail_path(shopping_detail) %></td>
        <td><%= link_to 'Destroy', shopping_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopping detail', new_shopping_detail_path %>

app/views/shopping_details/new.html.erb
<h1>New Shopping Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', shopping_details_path %>

app/views/shopping_details/show.html.erb
<%= image_tag @shopping_detail.image.url %>

<p>
  <strong>Description:</strong>
  <%= @shopping_detail.description %>
</p>

<%= link_to 'Edit', edit_shopping_detail_path(@shopping_detail) %> |
<%= link_to 'Back', shopping_details_path %>