config/routes.rb
Rails.application.routes.draw do

  resources :shopping_details
  delete 'shopping_infos/delete_shopping_info'

  post 'shopping_infos/upload_shopping_info'

  get 'budgets/show_budget'

  resources :products

  resources :sales

  resources :favourite_stores

=begin
  resource :user do
    resource :users
  end
=end

  # noinspection RubyResolve
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks'}

  root 'smartlist_app#dashboard_user'

  get 'dashboard_admin' => 'smartlist_app#dashboard_admin', as: :dashboard_admin

  get 'dashboard_store' => 'smartlist_app#dashboard_store', as: :dashboard_store

  post 'contact_us' => 'smartlist_app#contact_us', as: :contact_us

  get '/show_all_sales', to: 'smartlist_app#show_all_sales'

  # Recipe routes
  get 'recipes/show_recipes'

  get 'recipes/set_recipe_as_active_list'

  get 'recipes/add_recipe_to_active_list'

  delete 'recipes/delete_recipe'

  get 'recipes/delete_product_from_recipe'

  get 'recipes/add_product_to_recipe'

  get 'recipes/edit_recipe'

  get 'recipes/create_recipe'

  get '/show_recipe_constructor', to: 'recipes#show_recipe_constructor'

  post '/register_new_recipe', to: 'recipes#register_new_recipe'

  # FavouriteList routes
  get 'favourite_lists/show_favourite_lists'

  get 'favourite_lists/make_favourite_list_active'

  delete 'favourite_lists/delete_favourite_list'

  get 'favourite_lists/edit_favourite_list'

  post 'favourite_lists/create_favourite_list'

  get '/delete_from_favourite_list', to: 'favourite_lists#delete_from_favourite_list'

  get '/add_to_favourite_list', to: 'favourite_lists#add_to_favourite_list'

  post '/send_list_by_mail', to: 'favourite_lists#send_list_by_mail'

  # Admin routes
  get 'admin/show_users'

  get 'admin/show_stores'

  get 'admin/show_user'

  get 'admin/new_user'

  get 'admin/new_store'

  get 'admin/edit_user'

  post 'admin/create_user'

  post 'admin/update_user'

  delete 'admin/destroy_user'


  # Product routes
  get 'shopping_list' => '/show_all_active_products', to: 'products#show_all_active_products'

  get '/set_as_active', to: 'products#set_as_active'

  get '/set_as_inactive', to: 'products#set_as_inactive'

end

app/views/navbars/_navbar_admin.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
          <strong>SMARTLIST</strong>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'users', admin_show_users_path, class: 'link' %></li>
        <li><%= link_to 'stores', admin_show_stores_path, class: 'link' %></li>
        <!--<li class="dropdown">-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
          <!--<ul class="dropdown-menu">-->
            <!--<li><a href="#">Action</a></li>-->
            <!--<li><a href="#">Another action</a></li>-->
            <!--<li><a href="#">Something else here</a></li>-->
            <!--<li role="separator" class="divider"></li>-->
            <!--<li><a href="#">Separated link</a></li>-->
            <!--<li role="separator" class="divider"></li>-->
            <!--<li><a href="#">One more separated link</a></li>-->
          <!--</ul>-->
        <!--</li>-->
      </ul>
      <!--<form class="navbar-form navbar-left" role="search">-->
        <!--<div class="form-group">-->
          <!--<input type="text" class="form-control" placeholder="Search">-->
        <!--</div>-->
        <!--<button type="submit" class="btn btn-default">Submit</button>-->
      <!--</form>-->

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
             aria-haspopup="true" aria-expanded="false"><strong><!--signed in as --><%= current_user.email %></strong> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <!--<li><a href="#">Action</a></li>-->
            <li><%= # noinspection RubyResolve
                    link_to 'Edit profile', edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li>
              <%= # noinspection RubyResolve
                  link_to 'Sign out', destroy_user_session_path %>
            </li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/navbars/_navbar_store.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
          <strong>SMARTLIST</strong>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to 'add sale', new_sale_path %></li>
        <li> <%= link_to 'edit sale', sales_path %></li>
        <li><%= # noinspection RubyResolve
                link_to 'edit profile', edit_user_registration_path %></li>
        <!--<li class="dropdown">-->
        <!---->
        <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" -->
           <!--aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
        <!--<ul class="dropdown-menu">-->
            <!--<li><a href="#">add sale</a></li>-->
            <!--<li><a href="#">edit sale</a></li>-->
            <!--<li role="separator" class="divider"></li>-->
          <!--<li><a href="#">edit sale</a></li>-->
          <!--</ul>-->
        <!--</li>-->
      </ul>
      <!--<form class="navbar-form navbar-left" role="search">-->
        <!--<div class="form-group">-->
          <!--<input type="text" class="form-control" placeholder="Search">-->
        <!--</div>-->
        <!--<button type="submit" class="btn btn-default">Submit</button>-->
      <!--</form>-->
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
             aria-haspopup="true" aria-expanded="false"><strong><!--signed in as --><%= current_user.email %></strong> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <!--<li><a href="#">Action</a></li>-->
            <li><%= # noinspection RubyResolve
                    link_to 'Edit profile', edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li>
              <%= # noinspection RubyResolve
                  link_to 'Sign out', destroy_user_session_path %>
            </li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/navbars/_navbar_user.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
      <strong>SMARTLIST</strong>
          <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
             aria-haspopup="true" aria-expanded="false">smartlist <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'manage your products', products_path %></li>
            <li><%= link_to 'favourite lists', favourite_lists_show_favourite_lists_path %></li>
            <!--<li><a href="#">Something else here</a></li>-->
            <li role="separator" class="divider"></li>
            <li><%= link_to 'active shopping list', shopping_list_path %></a></li>
          </ul>
        </li>
        <li><%=  link_to 'recipes', recipes_show_recipes_path %></li>
        <li><%= link_to 'budget', budgets_show_budget_path %></li>
        <li><%= link_to 'favourite stores', favourite_stores_path %></li>
        <li><%= link_to 'sales', show_all_sales_path %></li>
        <li><%= link_to 'shopping info', shopping_details_path %></li>
      </ul>
      <!--<form class="navbar-form navbar-left" role="search">-->
        <!--<div class="form-group">-->
          <!--<input type="text" class="form-control" placeholder="Search">-->
        <!--</div>-->
        <!--<button type="submit" class="btn btn-default">Submit</button>-->
      <!--</form>-->
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
             aria-haspopup="true" aria-expanded="false"><strong><!--signed in as --><%= current_user.email %></strong> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <!--<li><a href="#">Action</a></li>-->
            <li><%= # noinspection RubyResolve
                    link_to 'Edit profile', edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li>
            <%= # noinspection RubyResolve
                link_to 'Sign out', destroy_user_session_path %>
            </li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>