config/routes.rb
Rails.application.routes.draw do

  resources :shopping_details
  delete 'shopping_infos/delete_shopping_info'

  post 'shopping_infos/upload_shopping_info'

  get 'budgets/show_budget'

  resources :products

  resources :sales

  resources :favourite_stores

=begin
  resource :user do
    resource :users
  end
=end

  # noinspection RubyResolve
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks'}

  root 'smartlist_app#dashboard_user'

  get 'dashboard_admin' => 'smartlist_app#dashboard_admin', as: :dashboard_admin

  get 'dashboard_store' => 'smartlist_app#dashboard_store', as: :dashboard_store

  post 'contact_us' => 'smartlist_app#contact_us', as: :contact_us

  get '/show_all_sales', to: 'smartlist_app#show_all_sales'

  # Recipe routes
  get 'recipes/show_recipes'

  get 'recipes/set_recipe_as_active_list'

  get 'recipes/add_recipe_to_active_list'

  delete 'recipes/delete_recipe'

  get 'recipes/delete_product_from_recipe'

  get 'recipes/add_product_to_recipe'

  get 'recipes/edit_recipe'

  get 'recipes/create_recipe'

  get '/show_recipe_constructor', to: 'recipes#show_recipe_constructor'

  post '/register_new_recipe', to: 'recipes#register_new_recipe'

  # FavouriteList routes
  get 'favourite_lists/show_favourite_lists'

  get 'favourite_lists/make_favourite_list_active'

  delete 'favourite_lists/delete_favourite_list'

  get 'favourite_lists/edit_favourite_list'

  post 'favourite_lists/create_favourite_list'

  get '/delete_from_favourite_list', to: 'favourite_lists#delete_from_favourite_list'

  get '/add_to_favourite_list', to: 'favourite_lists#add_to_favourite_list'

  post '/send_list_by_mail', to: 'favourite_lists#send_list_by_mail'

  # Admin routes
  get 'admin/show_users'

  get 'admin/show_stores'

  get 'admin/show_user'

  get 'admin/new_user'

  get 'admin/new_store'

  get 'admin/edit_user'

  post 'admin/create_user'

  post 'admin/update_user'

  delete 'admin/destroy_user'


  # Product routes
  get 'shopping_list' => '/show_all_active_products', to: 'products#show_all_active_products'

  get '/set_as_active', to: 'products#set_as_active'

  get '/set_as_inactive', to: 'products#set_as_inactive'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :budget
  belongs_to :user
  has_and_belongs_to_many :favourite_lists
end

app/controllers/products_controller.rb
# noinspection RubyResolve,RailsParamDefResolve
class ProductsController < ApplicationController
  before_filter :authenticate_user!, :usual_user?
  # before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.where(user_id: current_user.id)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  def show_all_active_products
    @active_products = Product.where(user_id: current_user.id, active: true)
    @products = show_all_user_products(user_id: current_user.id)
  end

  def show_all_user_products(user_id)
    Product.where(user_id)
  end

  def set_as_active
    @product = Product.find(params[:id])
    @product.update_attribute(:active, true)
    redirect_to shopping_list_url
  end

  def set_as_inactive
    @product = Product.find(params[:id])
    @product.update_attribute(:active, false)
    redirect_to shopping_list_url
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def usual_user?
    redirect_to '/' unless !current_user.admin? && !current_user.store?
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:user_id, :name, :price, :description, :store, :favourite_store_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, 'error') %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= # noinspection RubyResolve
        f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name, placeholder: 'your product name', cols: '40' %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price, class: :text_field, step: 0.01, placeholder: 'price', size: '42x10' %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, placeholder: 'product description', cols: '40' %>
  </div>
  <div class="field">
    <%= f.label :store %><br>
    <%= f.text_area :store, placeholder: 'where you buy it', cols: '40' %>
  </div>
    <br>
<!--  <div class="field">
    <%= #TODO: Saving of information about favourite store that sells the product
        #TODO: can be implemented in next version of the web page
        f.label :favourite_store_id %><br>
    <%= f.number_field :favourite_store_id %>
  </div>-->
  <div class="actions">
    <%= f.submit 'add product', class: 'button btn btn-sign-in' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<head>
  <% content_for :title, 'Manage your products' %>
</head>

<body>

<div class="top-content">

  <div class="inner-bg">

    <div class="container">

      <div class="row">
        <div class="col-sm-8 col-sm-offset-2 text">
          <h1 class="page-header"><strong>YOUR PRODUCTS</strong></h1>
        </div>
      </div>

      <div class="row">
        <div class="form-box">

          <div>
            <div class="panel panel-default">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-7 col-sm-10">
                    <h4>
                      <strong>PRODUCTS</strong>
                    </h4>
                  </div>
                  <div class="col-xs-5 col-sm-2">
                    <%= link_to 'add product', new_product_path, class: 'btn btn-success' %>
                  </div>
                </div>
              </div>
              <table class="table table-fixed">
                <thead>
                <tr>
                  <th class="col-xs-3 col-sm-3 col-md-3 col-lg-3">Name</th>
                  <th class="col-xs-2 col-sm-2 col-md-2 col-lg-2">Price</th>
                  <th class="col-sm-3 col-md-3 col-lg-3"><div class="hidden-xs">Description</div></th>
                  <th class="col-xs-3 col-sm-2 col-md-2 col-lg-2">Store</th>
                  <th class="col-xs-2 col-sm-1 col-md-1 col-lg-1"></th>
                  <th class="col-xs-2 col-sm-1 col-md-1 col-lg-1"></th>
                </tr>
                </thead>
                <tbody>
                <% @products.each do |product| %>
                    <tr>
                      <td class="col-xs-3 col-sm-3 col-md-3 col-lg-3 left-al-cell"><%= product.name %></td>
                      <td class="col-xs-2 col-sm-2 col-md-2 col-lg-2 left-al-cell"><%= product.price %></td>
                      <td class="col-sm-3 col-md-3 col-lg-3 left-al-cell">
                        <div class="hidden-xs"><%= product.description %></div>
                      </td>
                      <td class="col-xs-3 col-sm-2 col-md-2 col-lg-2 left-al-cell"><%= product.store %></td>
                      <td class="col-xs-2 col-sm-1 col-md-1 col-lg-1">
                        <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-info' %>
                      </td>
                      <td class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
                        <%= link_to 'delete', product, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-warning' %>
                      </td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>


</body>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Store:</strong>
  <%= @product.store %>
</p>

<!--<p>
  <strong>Favourite store:</strong>
  <%= @product.favourite_store_id %>
</p>-->

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/show_all_active_products.html.erb
<head>
  <% content_for :title, 'SHOPPING LIST' %>
</head>

<body>

<div class="top-content">

  <div class="inner-bg">

    <div class="container">

      <div class="row">
        <div class="col-sm-8 col-sm-offset-2 text">
          <h1 class="page-header"><strong>SHOPPING LIST</strong></h1>
        </div>
      </div>

      <div class="row">
        <div class="form-box">
          <div class="col-xs-12 col-sm-6 ">

            <div class="panel panel-default panel-danger">
              <div class="panel-heading">
                <h4>
                  <strong>Active list:</strong>
                </h4>
              </div>
              <div id="wrapper">
                <table class="table table-fixed">
                  <thead>
                  <tr>
                    <th class="col-xs-4">Name</th>
                    <th class="col-xs-6">Address</th>
                    <th class="col-xs-2"></th>
                  </tr>
                  </thead>
                  <tbody>

                  <% @active_products.each do |active_product| %>
                      <tr>
                        <td class="col-xs-4 left-al-cell"><%= active_product.name %></td>
                        <td class="col-xs-6 left-al-cell"><%= active_product.store %></td>
                        <td class="col-xs-2"><%= link_to 'done',
                                                         {controller: :products,
                                                          action: :set_as_inactive,
                                                          id: active_product.id},
                                                         class: 'btn btn-success' %></td>
                      </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
            </div>

            <%= link_to '#add_favourite_list', :remote => true, 'data-toggle' => 'modal', class: 'btn btn-info' do %>
                Add to favourites
            <% end %>
            <%= link_to '#send_as_email', :remote => true, 'data-toggle' => 'modal', class: 'btn btn-success' do %>
                Send as email
            <% end %>

            <!--Modal "Add as favourite list"-->
            <div class="modal" id="add_favourite_list" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
              <div class="modal-dialog" role="form">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title" id="modalLabel">Add to favourite lists</h3>
                  </div>
                  <div class="modal-body">
                    <div class="container">
                      <div class="row">
                        <div class="col-md-6">
                          <div class="well well-sm">
                            <%= # noinspection RubyResolve
                                form_tag(favourite_lists_create_favourite_list_path) do %>
                                <div class="row">
                                  <div class="col-md-6">
                                    <div class="form-group">
                                      <div class="field">
                                        <%= text_field_tag :name, nil, placeholder: 'Enter name of your list',
                                                           required: 'required' %>
                                      </div>
                                    </div>
                                  </div>
                                  <div class="col-md-6">
                                    <div class="actions">
                                      <%= submit_tag 'Add to favourites', class: 'button btn btn-sign-in pull-left' %>
                                    </div>
                                  </div>
                                </div>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div> <!--modal-body-->
                </div> <!--modal-content-->
              </div> <!--modal-dialog-->
            </div> <!--modal-->

            <!--Modal "Send shopping list as email"-->
            <div class="modal" id="send_as_email" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
              <div class="modal-dialog" role="form">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title" id="modalLabel">Send list as email</h3>
                  </div>
                  <div class="modal-body">
                    <div class="container">
                      <div class="row">
                        <div class="col-md-6">
                          <div class="well well-sm">

                            <%= # noinspection RubyResolve
                                form_tag(send_list_by_mail_path) do %>
                                <div class="row">
                                  <div class="col-md-6">
                                    <div class="form-group">
                                      <div class="field">
                                        <%= email_field_tag :email, nil, placeholder: 'Enter name of your list',
                                                           required: 'required' %>
                                      </div>
                                    </div>
                                  </div>
                                  <div class="col-md-6">
                                    <div class="actions">
                                      <%= submit_tag 'send list', class: 'button btn btn-sign-in pull-left' %>
                                    </div>
                                  </div>
                                </div>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div> <!--modal-body-->
                </div> <!--modal-content-->
              </div> <!--modal-dialog-->
            </div> <!--modal-->


          </div>
        </div>
        <div class="col-xs-12 col-sm-6">


          <div class="panel panel-default panel-success">
            <div class="panel-heading">
              <h4>
                <strong>Your products:</strong>
              </h4>
            </div>
            <div>
              <table class="table table-fixed">
                <thead>
                <tr>
                  <th class="col-xs-4">Name</th>
                  <th class="col-xs-6">Description</th>
                  <th class="col-xs-2"></th>
                </tr>
                </thead>
                <tbody>

                <% @products.each do |product| %>
                    <tr>
                      <td class="col-xs-4 left-al-cell"><%= product.name %></td>
                      <td class="col-xs-6 left-al-cell"><%= product.description %></td>
                      <td class="col-xs-2"><%= link_to 'add',
                                                       {action: :set_as_active, controller: :products,
                                                        id: product.id},
                                                       class: 'btn btn-warning' %></td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>


        </div>


      </div>

    </div>

  </div>

</div>

</body>