config/routes.rb
Rails.application.routes.draw do

  resources :shopping_details
  delete 'shopping_infos/delete_shopping_info'

  post 'shopping_infos/upload_shopping_info'

  get 'budgets/show_budget'

  resources :products

  resources :sales

  resources :favourite_stores

=begin
  resource :user do
    resource :users
  end
=end

  # noinspection RubyResolve
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks'}

  root 'smartlist_app#dashboard_user'

  get 'dashboard_admin' => 'smartlist_app#dashboard_admin', as: :dashboard_admin

  get 'dashboard_store' => 'smartlist_app#dashboard_store', as: :dashboard_store

  post 'contact_us' => 'smartlist_app#contact_us', as: :contact_us

  get '/show_all_sales', to: 'smartlist_app#show_all_sales'

  # Recipe routes
  get 'recipes/show_recipes'

  get 'recipes/set_recipe_as_active_list'

  get 'recipes/add_recipe_to_active_list'

  delete 'recipes/delete_recipe'

  get 'recipes/delete_product_from_recipe'

  get 'recipes/add_product_to_recipe'

  get 'recipes/edit_recipe'

  get 'recipes/create_recipe'

  get '/show_recipe_constructor', to: 'recipes#show_recipe_constructor'

  post '/register_new_recipe', to: 'recipes#register_new_recipe'

  # FavouriteList routes
  get 'favourite_lists/show_favourite_lists'

  get 'favourite_lists/make_favourite_list_active'

  delete 'favourite_lists/delete_favourite_list'

  get 'favourite_lists/edit_favourite_list'

  post 'favourite_lists/create_favourite_list'

  get '/delete_from_favourite_list', to: 'favourite_lists#delete_from_favourite_list'

  get '/add_to_favourite_list', to: 'favourite_lists#add_to_favourite_list'

  post '/send_list_by_mail', to: 'favourite_lists#send_list_by_mail'

  # Admin routes
  get 'admin/show_users'

  get 'admin/show_stores'

  get 'admin/show_user'

  get 'admin/new_user'

  get 'admin/new_store'

  get 'admin/edit_user'

  post 'admin/create_user'

  post 'admin/update_user'

  delete 'admin/destroy_user'


  # Product routes
  get 'shopping_list' => '/show_all_active_products', to: 'products#show_all_active_products'

  get '/set_as_active', to: 'products#set_as_active'

  get '/set_as_inactive', to: 'products#set_as_inactive'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :user
end

app/controllers/sales_controller.rb
# noinspection ALL
class SalesController < ApplicationController
  before_filter :authenticate_user!, :store?
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.where(user_id: current_user.id)
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:user_id, :name, :expiry_date, :image_url)
    end

    def store?
        redirect_to '/' unless current_user.store?
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name, placeholder: 'add descriptopn/title of your sale', cols: "40" %>
  </div>
  <div class="field">
    <%= f.label :expiry_date %><br>
    <%= f.datetime_select :expiry_date %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_area :image_url, placeholder: 'http://site.no/image.png', cols: "40" %>
  </div>
    <br>
  <div class="actions">
    <%= f.submit 'add sale', class: 'button btn btn-sign-in' %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<head>
  <% content_for :title, 'Manage your sales' %>
</head>

<body>

<div class="top-content">

  <div class="inner-bg">

    <div class="container">

      <div class="row">
        <div class="col-sm-8 col-sm-offset-2 text">
          <h1 class="page-header"><strong>YOUR SALES</strong></h1>
        </div>
      </div>

      <div class="row">
        <div class="form-box">

          <div>
            <div class="panel panel-default">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-7 col-sm-9">
                    <h4>
                      <strong>SALES</strong>
                    </h4>
                  </div>
                  <div class="col-xs-5 col-sm-3">
                    <%= # noinspection RubyResolve
                        link_to 'add sale', new_sale_path, class: 'btn btn-success' %>
                  </div>
                </div>
              </div>
              <table class="table table-fixed">
                <thead>
                <tr>
                  <th class="col-xs-4 col-sm-3 col-md-3 col-lg-3">Name</th>
                  <th class="col-xs-4 col-sm-3 col-md-3 col-lg-3">Expiry Date</th>
                  <th class="col-sm-3 col-md-3 col-lg-3"><div class="hidden-xs">Image URL</div></th>
                  <th class="col-xs-2 col-sm-1 col-md-1 col-lg-1"></th>
                  <th class="col-xs-2 col-sm-1 col-md-1 col-lg-1"></th>
                </tr>
                </thead>
                <tbody>
                <!--TODO: Delete show button-->
                <% @sales.each do |sale| %>
                    <tr>
                      <td class="col-xs-4 col-sm-3 col-md-3 col-lg-3 left-al-cell"><%= sale.name %></td>
                      <td class="col-xs-4 col-sm-3 col-md-3 col-lg-3 left-al-cell">
                        <%= sale.expiry_date.strftime('%d.%m.%Y %H:%M') %>
                      </td>
                      <td class="col-sm-3 col-md-3 col-lg-3 left-al-cell">
                        <div class="hidden-xs"><%= sale.image_url %></div>
                        </td>
                      <td class="col-xs-2 col-sm-1 col-md-1 col-lg-1">
                        <%= # noinspection RubyResolve
                            link_to 'Edit', edit_sale_path(sale), class: 'btn btn-info' %>
                      </td>
                      <td class="col-xs-2 col-sm-1 col-md-1 col-lg-1">
                        <%= link_to 'delete', sale, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning' %>
                      </td>
                    </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>


</body>

app/views/sales/new.html.erb
<h1>Add a new sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @sale.name %>
</p>

<p>
  <strong>Expiry date:</strong>
  <%= @sale.expiry_date %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @sale.image_url %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>